// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sb-counter/app/dao/internal"
)

// counterDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type counterDao struct {
	*internal.CounterDao
}

var (
	// Counter is globally public accessible object for table counter operations.
	Counter = counterDao{
		internal.NewCounterDao(),
	}
)

// Fill with you ideas below.
