// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Counter is the golang structure for table counter.
type Counter struct {
	Id        string      `json:"id"        description:""`
	Db        string      `json:"db"        description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	Ip        string      `json:"ip"        description:""`
}
