// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Counter is the golang structure of table counter for DAO operations like Where/Data.
type Counter struct {
	g.Meta    `orm:"table:counter, do:true"`
	Id        interface{} //
	Db        interface{} //
	CreatedAt *gtime.Time //
	Ip        interface{} //
}
