// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// Counter is the golang structure for table counter.
type Counter struct {
	Id        string      `orm:"id"         json:"id"        description:""`
	Db        string      `orm:"db"         json:"db"        description:""`
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt" description:""`
	Ip        string      `orm:"ip"         json:"ip"        description:""`
}
