// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"image"
	"sb-counter/internal/consts"
)

type (
	ICounter interface {
		GetUser(ctx context.Context, userPath string) *consts.CounterUser
		DrawCard(ctx context.Context, today, all, yesterday, beforeYesterday int) []byte
		GetCardBackground(ctx context.Context) *image.RGBA
	}
)

var (
	localCounter ICounter
)

func Counter() ICounter {
	if localCounter == nil {
		panic("implement not found for interface ICounter, forgot register?")
	}
	return localCounter
}

func RegisterCounter(i ICounter) {
	localCounter = i
}
