// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"sb-counter/internal/consts"
)

type (
	IDatabase interface {
		Add(ctx context.Context, db string, ip string) error
		FetchData(ctx context.Context, db string) *consts.CounterData
	}
)

var (
	localDatabase IDatabase
)

func Database() IDatabase {
	if localDatabase == nil {
		panic("implement not found for interface IDatabase, forgot register?")
	}
	return localDatabase
}

func RegisterDatabase(i IDatabase) {
	localDatabase = i
}
