// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sb-counter/internal/dao/internal"
)

// internalCounterDao is internal type for wrapping internal DAO implements.
type internalCounterDao = *internal.CounterDao

// counterDao is the data access object for table counter.
// You can define custom methods on it to extend its functionality as you wish.
type counterDao struct {
	internalCounterDao
}

var (
	// Counter is globally public accessible object for table counter operations.
	Counter = counterDao{
		internal.NewCounterDao(),
	}
)

// Fill with you ideas below.
